#!/bin/bash

# Source: https://github.com/doegox/todo.txt-cli/blob/extras/todo.actions.d/add
# Edited by Jaan Janesmae (removed marking it as done functionality)

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    add pri|p PRIORITY \"THING I NEED TO DO +project @context\""
    echo "      Adds an item and prioritizes it in one step"
    echo ""
    exit
}

PRIORITY=false
DO=false
if [ x"$1" = x"pri" -o x"$1" = x"p" ] && [[ x"$2" = x[a-zA-Z] ]]; then
    PRIORITY=$2
    shift
    shift
fi

# call back to the main script to add
if "$TODO_SH" command add "$@"; then
    # figure out the line of what we just added, and "do" it
    line=`sed -n '$ =' "$TODO_FILE"`
    [ $PRIORITY != false ] && "$TODO_SH" command pri "$line" $PRIORITY
fi