#!/usr/bin/env bash

# Source: https://github.com/yatil/todo.txt-addons/blob/master/schedule
# Edited by Jaan Janesmae (removed mv sub-option, set due: instead of t:)

action=$1
shift
item=$1
shift
param="$*"

pattern=" due:\([0-9]\{2,4\}[^A-Za-z0-9]\)\{2\}[0-9]\{2,4\}" # set due date

function usage {

	echo "    $(basename $0)"
	echo "      List items with a due date."
	echo "    $(basename $0) ITEM# DATETIME"
	echo "      Sets due date of an item."
	echo "    $(basename $0) ITEM# rm"
	echo "      Removes due date of an item."
	echo "      Examples:"
	echo "        $ $TODO_SH $(basename $0) 42 tomorrow"
	echo "        $ $TODO_SH $(basename $0) 42 5 days"
	echo "        $ $TODO_SH $(basename $0) 42 44"
	echo "        $ $TODO_SH $(basename $0) 42 2018-10-30"
	echo "        $ $TODO_SH $(basename $0) 42 rm"
	echo ""
	exit
}

function list {
	$TODO_FULL_SH -x list | grep "$pattern"
}

function add {
	item=$1
	threshold=$2

	re='^-?[0-9]+$'
	[[ $2 =~ $re ]] && threshold=$2" days"

	flag=`sed -e "$item!d" "$TODO_FILE" | grep "$pattern"`

	if [ -z "$flag" ]; then
		$TODO_FULL_SH append $item "due:"`gdate -d "$threshold" +%F`
	else
		replace $item "$threshold"
	fi
}

function remove {
	item=$1
	task=`sed -e "$item!d" \
			-e "s/^[0-9]* //" \
			-e "s/^([A-Z])* //" \
			-e "s/$pattern//" \
			"$TODO_FILE"` # remove item number, priority and threshold
	$TODO_FULL_SH replace $item "$task" # NB: retains priority
}

function replace {
	item=$1
	threshold=$2
	remove $item
	add $item "$threshold"
}

[ "$action" = "usage" ] && usage

if [ -z $item ]; then
	list
elif [ "$param" = "rm" ]; then
	remove $item
else
	add $item "$param"
fi