"" General vim config ""

" Basics

set nocompatible            " not compatible with vi
set autoread                " detect when a file is changed
set textwidth=120
set number                  " Display current line number
set relativenumber          " Display relative line numbers

" Usability ;)

syntax on
set cursorline
set background=dark
highlight clear SignColumn
set mouse=a                 " Make mouse usable
nnoremap ; :

" Invisible characters

set list
set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

" Tab control

set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

" Bells

set noerrorbells
set visualbell

" Search

set hlsearch
set incsearch
set ignorecase
set showmatch
set smartcase

" Scrolling

set scrolloff=4
set sidescrolloff=15
set sidescroll=1

