"" General vim config ""

" Load Plugins

source ~/.vim/plugins.vim

" Basics
set nocompatible				" Turn on improvements
set encoding=utf-8 nobomb			" Set Character encoding without BOM
set binary					" Binary mode for noeol
set noeol					" Remove empty newline at the end of the file
set title					" Inherit title for terminal
set ruler					" Show line and col number
set showcmd					" Show incomplete cmds down the bottom
set autoread					" Reload files changed outside vim
set textwidth=80
set fo-=t					" Prevent auto word wrapping

" Centralize backups, swapfiles and undo history

set backupdir=~/.vim/backups//
set directory=~/.vim/swaps//
set undodir=~/.vim/undo//

" Usability ;)

set number					" Display current line number
set relativenumber				" Display relative line numbers

syntax on					" Enable syntax highlighting
set showmatch					" Show matching brackets
set cursorline					" Underline the current line
set background=dark				" Set dark background

let mapleader=","				" Change mapleader

highlight clear SignColumn			" vim-gitgutter fix
nnoremap ; :

highlight ColorColumn ctermbg=red
call matchadd('colorcolumn', '\%81v', 100)

highlight ListChars ctermfg=Cyan

set backspace=indent,eol,start			" Fix backspace in Vim8
set mouse=a					" Make mouse usable

nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<Esc>	" <esc><esc> clears search highlights

" Invisible characters

set list
set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪	

" Tab control

set autoindent					" Copy indent from previous line 
set smartindent
set smarttab
set tabstop=8					" Number of spaces that a <Tab> counts for
set softtabstop=0				" Number of tabs that a <Tab> counts for
set shiftwidth=8				" Number of spaces to use for (auto) indent
set noexpandtab					" Use tabs instead of spaces

" Bells

set noerrorbells
set visualbell

" Search

set hlsearch					" Highlight search matches
set incsearch					" Show matches while searching
set ignorecase					" Ignore case when searching
set smartcase					" Override ignorecase when needed

" Scrolling

set nowrap					" Stop linebraking
set scrolloff=10				" Keep 5 lines below cursor
set sidescrolloff=15				" Keep 5 columns when scrolling vertically
set sidescroll=1				" Columns to scroll vertically

"" Plugin Configurations ""

source ~/.vim/plugins/nerdtree.vim
source ~/.vim/plugins/vimoutliner.vim
