"" General vim config ""

" Basics

set nocompatible
set autoread				" Detect when a file is changed
set textwidth=120
set encoding=utf-8 nobomb
set binary
set noeol					" Remove empty newline at the end of the file
set title

set number					" Display current line number
set relativenumber			" Display relative line numbers

let mapleader=","			" Change mapleader

" Centralize backups, swapfiles and undo history

set backupdir=~/.vim/backups
set directory=~/.vim/swaps
if exists("&undodir")
	set undodir=~/.vim/undo
endif

" Usability ;)

syntax on
set cursorline
set background=dark
highlight clear SignColumn
nnoremap ; :

set mouse=a					" Make mouse usable

" Invisible characters

set list
set listchars=tab:→\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

" Tab control

set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set noexpandtab				" Use tabs instead of spaces

" Bells

set noerrorbells
set visualbell

" Search

set hlsearch
set incsearch
set ignorecase
set showmatch
set smartcase

" Scrolling

set scrolloff=4
set sidescrolloff=15
set sidescroll=1
