##  Zsh general config ##

# Include specialized configs

source ${HOME}/.zsh/environment.zsh		# Settings for environment
source ${HOME}/.zsh/history.zsh			# Settings for keeping a history

source ${HOME}/.zsh/colors.zsh
source ${HOME}/.zsh/setopts.zsh
source ${HOME}/.zsh/prompt.zsh
source ${HOME}/.zsh/completion.zsh
source ${HOME}/.zsh/aliases.zsh

source ${HOME}/.zsh/plugins.zsh			# Settings for plugins
