##  Zsh general config ##

# Include specialized configs

source ~/.zsh/environment.zsh		# Environment settings
source ~/.zsh/history.zsh		# Keeping history settings

source ~/.zsh/colors.zsh
source ~/.zsh/setopts.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh

# Zsh Plugins

test -e "${HOME}/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" && source "${HOME}/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"				# Auto Suggestions
test -e "${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" && source "${HOME}/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"		# Syntax highlighting

